repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        files: ^src/

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E203,E731,F541,F841,E266', '--exclude=tests/*']

  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
        args: ['--profile',  'black']
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: name-tests-test
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: create requirements
        name: create requirements
        entry: sh write_requirements.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]
      - id: pytest-check
        name: run pytest tests
        entry: pytest -v
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
